spring.application.name=serveme

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

serve-me.images.path=${IMAGES_PATH}
serve-me.images.base-url=${IMAGES_BASE_URL}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never